#name, main, version and api are required
name: AutoPluginUpdater
main: tpguy825\AutoPluginUpdater\Main
src-namespace-prefix: tpguy825\AutoPluginUpdater
version: 0.0.1
api: 4.6.1

load: POSTWORLD
author: tpguy825
description: Plugin to help automatically keep your plugins up to date!
website: https://github.com/tpguy825/AutoPluginUpdater
